export const TOGGLE_BURGER = 'APP/TOGGLE_BURGER';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const TOGGLE_LOADER = 'APP/TOGGLE_LOADER';
export const FETCH_SCRIPT = 'SCRIPT/FETCH_SCRIPT';